FSI_DIR = $(TK_INSTALL_DIR)
FSI_INCDIR = $(TK_INCDIR)
FSI_LIBDIR = $(TK_LIBDIR)
FSI_BINDIR = $(TK_BINDIR)
FSI_EXEDIR = $(TK_EXEDIR)

CXXFLAGS += -I$(FSI_INCDIR)
INCFLAGS += -I$(FSI_INCDIR)
LIBS     += -L$(FSI_LIBDIR)
