ROOT_UTIL_DIR = $(TK_ROOT)
ROOT_UTIL_BINDIR = $(TK_BINDIR)
ROOT_UTIL_EXEDIR = $(TK_BINDIR)
ROOT_UTIL_LIBDIR = $(TK_LIBDIR)
ROOT_UTIL_INCDIR = $(TK_INCDIR)

CXXFLAGS += -I$(ROOT_UTIL_INCDIR)
INCFLAGS += -I$(ROOT_UTIL_INCDIR)
LIBS     += -L$(ROOT_UTIL_LIBDIR) -lroot_util
