ZEUS_DIR = $(TK_INSTALL_DIR)
ZEUS_BINDIR = $(ZEUS_DIR)/bin
ZEUS_EXEDIR = $(ZEUS_BINDIR)
ZEUS_LIBDIR = $(ZEUS_DIR)/lib
ZEUS_INCDIR = $(ZEUS_DIR)/include

CXXFLAGS += -I$(ZEUS_INCDIR)
INCFLAGS += -I$(ZEUS_INCDIR)

ZS = OFF

ifeq ($(ZS), ON)
  CXXFLAGS += -DLINK_TO_ZEUS_SOFTWARES
  FFLAGS   += -DLINK_TO_ZEUS_SOFTWARES
  OBJDIR = obj/zeus
endif

