ATLAS_DIR = $(TK_INSTALL_DIR)
ATLAS_BINDIR = $(ATLAS_DIR)/bin
ATLAS_EXEDIR = $(ATLAS_BINDIR)
ATLAS_LIBDIR = $(ATLAS_DIR)/lib
ATLAS_INCDIR = $(ATLAS_DIR)/include

CXXFLAGS += -I$(ATLAS_INCDIR)
INCFLAGS += -I$(ATLAS_INCDIR)
LIBS += -L$(ATLAS_LIBDIR)
